// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dritelabs/accounts/internal/database/models"
)

func newAddress(db *gorm.DB, opts ...gen.DOOption) address {
	_address := address{}

	_address.addressDo.UseDB(db, opts...)
	_address.addressDo.UseModel(&models.Address{})

	tableName := _address.addressDo.TableName()
	_address.ALL = field.NewAsterisk(tableName)
	_address.ID = field.NewField(tableName, "id")
	_address.CreatedAt = field.NewTime(tableName, "created_at")
	_address.UpdatedAt = field.NewTime(tableName, "updated_at")
	_address.DeletedAt = field.NewField(tableName, "deleted_at")
	_address.UserID = field.NewField(tableName, "user_id")
	_address.City = field.NewField(tableName, "city")
	_address.Country = field.NewField(tableName, "country")
	_address.Line1 = field.NewString(tableName, "line1")
	_address.Line2 = field.NewField(tableName, "line2")
	_address.PhoneNumber = field.NewString(tableName, "phone_number")
	_address.PostalCode = field.NewInt32(tableName, "postal_code")
	_address.Region = field.NewString(tableName, "region")
	_address.User = addressBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		DefaultShippingAddress: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.DefaultShippingAddress", "models.Address"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.DefaultShippingAddress.User", "models.User"),
			},
		},
		DefaultBillingAddress: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.DefaultBillingAddress", "models.Address"),
		},
		Profile: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Profile", "models.Profile"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Profile.User", "models.User"),
			},
		},
		Addresses: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Addresses", "models.Address"),
		},
		Clients: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Approvals struct {
				field.RelationField
				Scopes struct {
					field.RelationField
					Approvals struct {
						field.RelationField
					}
					Clients struct {
						field.RelationField
					}
				}
				Clients struct {
					field.RelationField
				}
				Users struct {
					field.RelationField
				}
			}
			Scopes struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Clients", "models.Client"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Clients.User", "models.User"),
			},
			Approvals: struct {
				field.RelationField
				Scopes struct {
					field.RelationField
					Approvals struct {
						field.RelationField
					}
					Clients struct {
						field.RelationField
					}
				}
				Clients struct {
					field.RelationField
				}
				Users struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Clients.Approvals", "models.Approval"),
				Scopes: struct {
					field.RelationField
					Approvals struct {
						field.RelationField
					}
					Clients struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("User.Clients.Approvals.Scopes", "models.Scope"),
					Approvals: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Clients.Approvals.Scopes.Approvals", "models.Approval"),
					},
					Clients: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Clients.Approvals.Scopes.Clients", "models.Client"),
					},
				},
				Clients: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Clients.Approvals.Clients", "models.Client"),
				},
				Users: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Clients.Approvals.Users", "models.User"),
				},
			},
			Scopes: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Clients.Scopes", "models.Scope"),
			},
		},
		Approvals: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Approvals", "models.Approval"),
		},
	}

	_address.fillFieldMap()

	return _address
}

type address struct {
	addressDo

	ALL         field.Asterisk
	ID          field.Field
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	UserID      field.Field
	City        field.Field
	Country     field.Field
	Line1       field.String
	Line2       field.Field
	PhoneNumber field.String
	PostalCode  field.Int32
	Region      field.String
	User        addressBelongsToUser

	fieldMap map[string]field.Expr
}

func (a address) Table(newTableName string) *address {
	a.addressDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a address) As(alias string) *address {
	a.addressDo.DO = *(a.addressDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *address) updateTableName(table string) *address {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.UserID = field.NewField(table, "user_id")
	a.City = field.NewField(table, "city")
	a.Country = field.NewField(table, "country")
	a.Line1 = field.NewString(table, "line1")
	a.Line2 = field.NewField(table, "line2")
	a.PhoneNumber = field.NewString(table, "phone_number")
	a.PostalCode = field.NewInt32(table, "postal_code")
	a.Region = field.NewString(table, "region")

	a.fillFieldMap()

	return a
}

func (a *address) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *address) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["city"] = a.City
	a.fieldMap["country"] = a.Country
	a.fieldMap["line1"] = a.Line1
	a.fieldMap["line2"] = a.Line2
	a.fieldMap["phone_number"] = a.PhoneNumber
	a.fieldMap["postal_code"] = a.PostalCode
	a.fieldMap["region"] = a.Region

}

func (a address) clone(db *gorm.DB) address {
	a.addressDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a address) replaceDB(db *gorm.DB) address {
	a.addressDo.ReplaceDB(db)
	return a
}

type addressBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	DefaultShippingAddress struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	DefaultBillingAddress struct {
		field.RelationField
	}
	Profile struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Addresses struct {
		field.RelationField
	}
	Clients struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Approvals struct {
			field.RelationField
			Scopes struct {
				field.RelationField
				Approvals struct {
					field.RelationField
				}
				Clients struct {
					field.RelationField
				}
			}
			Clients struct {
				field.RelationField
			}
			Users struct {
				field.RelationField
			}
		}
		Scopes struct {
			field.RelationField
		}
	}
	Approvals struct {
		field.RelationField
	}
}

func (a addressBelongsToUser) Where(conds ...field.Expr) *addressBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a addressBelongsToUser) WithContext(ctx context.Context) *addressBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a addressBelongsToUser) Model(m *models.Address) *addressBelongsToUserTx {
	return &addressBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type addressBelongsToUserTx struct{ tx *gorm.Association }

func (a addressBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a addressBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a addressBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a addressBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a addressBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a addressBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type addressDo struct{ gen.DO }

type IAddressDo interface {
	gen.SubQuery
	Debug() IAddressDo
	WithContext(ctx context.Context) IAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAddressDo
	WriteDB() IAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAddressDo
	Not(conds ...gen.Condition) IAddressDo
	Or(conds ...gen.Condition) IAddressDo
	Select(conds ...field.Expr) IAddressDo
	Where(conds ...gen.Condition) IAddressDo
	Order(conds ...field.Expr) IAddressDo
	Distinct(cols ...field.Expr) IAddressDo
	Omit(cols ...field.Expr) IAddressDo
	Join(table schema.Tabler, on ...field.Expr) IAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAddressDo
	Group(cols ...field.Expr) IAddressDo
	Having(conds ...gen.Condition) IAddressDo
	Limit(limit int) IAddressDo
	Offset(offset int) IAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAddressDo
	Unscoped() IAddressDo
	Create(values ...*models.Address) error
	CreateInBatches(values []*models.Address, batchSize int) error
	Save(values ...*models.Address) error
	First() (*models.Address, error)
	Take() (*models.Address, error)
	Last() (*models.Address, error)
	Find() ([]*models.Address, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Address, err error)
	FindInBatches(result *[]*models.Address, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Address) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAddressDo
	Assign(attrs ...field.AssignExpr) IAddressDo
	Joins(fields ...field.RelationField) IAddressDo
	Preload(fields ...field.RelationField) IAddressDo
	FirstOrInit() (*models.Address, error)
	FirstOrCreate() (*models.Address, error)
	FindByPage(offset int, limit int) (result []*models.Address, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithNameAndRole(name string, role string) (result []models.Address, err error)
}

// SELECT * FROM @@table WHERE name = @name{{if role !=""}} AND role = @role{{end}}
func (a addressDo) FilterWithNameAndRole(name string, role string) (result []models.Address, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM addresses WHERE name = ? ")
	if role != "" {
		params = append(params, role)
		generateSQL.WriteString("AND role = ? ")
	}

	var executeSQL *gorm.DB

	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result)
	err = executeSQL.Error
	return
}

func (a addressDo) Debug() IAddressDo {
	return a.withDO(a.DO.Debug())
}

func (a addressDo) WithContext(ctx context.Context) IAddressDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a addressDo) ReadDB() IAddressDo {
	return a.Clauses(dbresolver.Read)
}

func (a addressDo) WriteDB() IAddressDo {
	return a.Clauses(dbresolver.Write)
}

func (a addressDo) Session(config *gorm.Session) IAddressDo {
	return a.withDO(a.DO.Session(config))
}

func (a addressDo) Clauses(conds ...clause.Expression) IAddressDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a addressDo) Returning(value interface{}, columns ...string) IAddressDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a addressDo) Not(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a addressDo) Or(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a addressDo) Select(conds ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a addressDo) Where(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a addressDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IAddressDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a addressDo) Order(conds ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a addressDo) Distinct(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a addressDo) Omit(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a addressDo) Join(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a addressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a addressDo) RightJoin(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a addressDo) Group(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a addressDo) Having(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a addressDo) Limit(limit int) IAddressDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a addressDo) Offset(offset int) IAddressDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a addressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAddressDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a addressDo) Unscoped() IAddressDo {
	return a.withDO(a.DO.Unscoped())
}

func (a addressDo) Create(values ...*models.Address) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a addressDo) CreateInBatches(values []*models.Address, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a addressDo) Save(values ...*models.Address) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a addressDo) First() (*models.Address, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Address), nil
	}
}

func (a addressDo) Take() (*models.Address, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Address), nil
	}
}

func (a addressDo) Last() (*models.Address, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Address), nil
	}
}

func (a addressDo) Find() ([]*models.Address, error) {
	result, err := a.DO.Find()
	return result.([]*models.Address), err
}

func (a addressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Address, err error) {
	buf := make([]*models.Address, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a addressDo) FindInBatches(result *[]*models.Address, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a addressDo) Attrs(attrs ...field.AssignExpr) IAddressDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a addressDo) Assign(attrs ...field.AssignExpr) IAddressDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a addressDo) Joins(fields ...field.RelationField) IAddressDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a addressDo) Preload(fields ...field.RelationField) IAddressDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a addressDo) FirstOrInit() (*models.Address, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Address), nil
	}
}

func (a addressDo) FirstOrCreate() (*models.Address, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Address), nil
	}
}

func (a addressDo) FindByPage(offset int, limit int) (result []*models.Address, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a addressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a addressDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a addressDo) Delete(models ...*models.Address) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *addressDo) withDO(do gen.Dao) *addressDo {
	a.DO = *do.(*gen.DO)
	return a
}
