// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file drite/account/v1/application_type.proto (package drite.account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum drite.account.v1.ApplicationType
 */
export enum ApplicationType {
  /**
   * @generated from enum value: APPLICATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPLICATION_TYPE_WEB = 1;
   */
  WEB = 1,

  /**
   * @generated from enum value: APPLICATION_TYPE_NATIVE = 2;
   */
  NATIVE = 2,

  /**
   * @generated from enum value: APPLICATION_TYPE_BROWSER = 3;
   */
  BROWSER = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ApplicationType)
proto3.util.setEnumType(ApplicationType, "drite.account.v1.ApplicationType", [
  { no: 0, name: "APPLICATION_TYPE_UNSPECIFIED" },
  { no: 1, name: "APPLICATION_TYPE_WEB" },
  { no: 2, name: "APPLICATION_TYPE_NATIVE" },
  { no: 3, name: "APPLICATION_TYPE_BROWSER" },
]);

