// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file drite/account/v1/grant_type.proto (package drite.account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum drite.account.v1.GrantType
 */
export enum GrantType {
  /**
   * @generated from enum value: GRANT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GRANT_TYPE_AUTHORIZATION_CODE = 1;
   */
  AUTHORIZATION_CODE = 1,

  /**
   * @generated from enum value: GRANT_TYPE_CLIENT_CREDENTIALS = 2;
   */
  CLIENT_CREDENTIALS = 2,

  /**
   * @generated from enum value: GRANT_TYPE_REFRESH_TOKEN = 3;
   */
  REFRESH_TOKEN = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(GrantType)
proto3.util.setEnumType(GrantType, "drite.account.v1.GrantType", [
  { no: 0, name: "GRANT_TYPE_UNSPECIFIED" },
  { no: 1, name: "GRANT_TYPE_AUTHORIZATION_CODE" },
  { no: 2, name: "GRANT_TYPE_CLIENT_CREDENTIALS" },
  { no: 3, name: "GRANT_TYPE_REFRESH_TOKEN" },
]);

