// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file drite/account/v1/jwk.proto (package drite.account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message drite.account.v1.Jwk
 */
export class Jwk extends Message<Jwk> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string client_id = 3;
   */
  clientId = "";

  /**
   * @generated from field: google.protobuf.Any jwk = 8;
   */
  jwk?: Any;

  /**
   * @generated from field: repeated string scopes = 4;
   */
  scopes: string[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Jwk>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "drite.account.v1.Jwk";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "jwk", kind: "message", T: Any },
    { no: 4, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Jwk {
    return new Jwk().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Jwk {
    return new Jwk().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Jwk {
    return new Jwk().fromJsonString(jsonString, options);
  }

  static equals(a: Jwk | PlainMessage<Jwk> | undefined, b: Jwk | PlainMessage<Jwk> | undefined): boolean {
    return proto3.util.equals(Jwk, a, b);
  }
}

/**
 * @generated from message drite.account.v1.GetJwksRequest
 */
export class GetJwksRequest extends Message<GetJwksRequest> {
  constructor(data?: PartialMessage<GetJwksRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "drite.account.v1.GetJwksRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJwksRequest {
    return new GetJwksRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJwksRequest {
    return new GetJwksRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJwksRequest {
    return new GetJwksRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetJwksRequest | PlainMessage<GetJwksRequest> | undefined, b: GetJwksRequest | PlainMessage<GetJwksRequest> | undefined): boolean {
    return proto3.util.equals(GetJwksRequest, a, b);
  }
}

/**
 * @generated from message drite.account.v1.GetJwksResponse
 */
export class GetJwksResponse extends Message<GetJwksResponse> {
  /**
   * @generated from field: google.protobuf.Any jwks = 1;
   */
  jwks?: Any;

  constructor(data?: PartialMessage<GetJwksResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "drite.account.v1.GetJwksResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "jwks", kind: "message", T: Any },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJwksResponse {
    return new GetJwksResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJwksResponse {
    return new GetJwksResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJwksResponse {
    return new GetJwksResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetJwksResponse | PlainMessage<GetJwksResponse> | undefined, b: GetJwksResponse | PlainMessage<GetJwksResponse> | undefined): boolean {
    return proto3.util.equals(GetJwksResponse, a, b);
  }
}

