// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file drite/account/v1/public_keys_configuration.proto (package drite.account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum drite.account.v1.PublicKeysConfiguration
 */
export enum PublicKeysConfiguration {
  /**
   * @generated from enum value: PUBLIC_KEYS_CONFIGURATION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PUBLIC_KEYS_CONFIGURATION_LOCAL = 1;
   */
  LOCAL = 1,

  /**
   * @generated from enum value: PUBLIC_KEYS_CONFIGURATION_REMOTE = 2;
   */
  REMOTE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(PublicKeysConfiguration)
proto3.util.setEnumType(PublicKeysConfiguration, "drite.account.v1.PublicKeysConfiguration", [
  { no: 0, name: "PUBLIC_KEYS_CONFIGURATION_UNSPECIFIED" },
  { no: 1, name: "PUBLIC_KEYS_CONFIGURATION_LOCAL" },
  { no: 2, name: "PUBLIC_KEYS_CONFIGURATION_REMOTE" },
]);

