// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file drite/account/v1/response_type.proto (package drite.account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum drite.account.v1.ResponseType
 */
export enum ResponseType {
  /**
   * @generated from enum value: RESPONSE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RESPONSE_TYPE_CODE = 1;
   */
  CODE = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(ResponseType)
proto3.util.setEnumType(ResponseType, "drite.account.v1.ResponseType", [
  { no: 0, name: "RESPONSE_TYPE_UNSPECIFIED" },
  { no: 1, name: "RESPONSE_TYPE_CODE" },
]);

