// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file grant_type.proto (package pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum pb.GrantType
 */
export enum GrantType {
  /**
   * @generated from enum value: AUTHORIZATION_CODE = 0;
   */
  AUTHORIZATION_CODE = 0,

  /**
   * @generated from enum value: CLIENT_CREDENTIALS = 1;
   */
  CLIENT_CREDENTIALS = 1,

  /**
   * @generated from enum value: REFRESH_TOKEN = 2;
   */
  REFRESH_TOKEN = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(GrantType)
proto3.util.setEnumType(GrantType, "pb.GrantType", [
  { no: 0, name: "AUTHORIZATION_CODE" },
  { no: 1, name: "CLIENT_CREDENTIALS" },
  { no: 2, name: "REFRESH_TOKEN" },
]);

