// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file refresh_token_rotation_type.proto (package pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum pb.RefreshTokenRotationType
 */
export enum RefreshTokenRotationType {
  /**
   * @generated from enum value: ROTATE = 0;
   */
  ROTATE = 0,

  /**
   * @generated from enum value: STATIC = 1;
   */
  STATIC = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(RefreshTokenRotationType)
proto3.util.setEnumType(RefreshTokenRotationType, "pb.RefreshTokenRotationType", [
  { no: 0, name: "ROTATE" },
  { no: 1, name: "STATIC" },
]);

