// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file token_endpoint_auth_method.proto (package pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum pb.TokenEndpointAuthMethod
 */
export enum TokenEndpointAuthMethod {
  /**
   * @generated from enum value: CLIENT_SECRET_BASIC = 0;
   */
  CLIENT_SECRET_BASIC = 0,

  /**
   * @generated from enum value: PRIVATE_KEY_JWT = 1;
   */
  PRIVATE_KEY_JWT = 1,

  /**
   * @generated from enum value: NONE = 2;
   */
  NONE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TokenEndpointAuthMethod)
proto3.util.setEnumType(TokenEndpointAuthMethod, "pb.TokenEndpointAuthMethod", [
  { no: 0, name: "CLIENT_SECRET_BASIC" },
  { no: 1, name: "PRIVATE_KEY_JWT" },
  { no: 2, name: "NONE" },
]);

